import { useEffect, useState } from 'react'
import { Plus, Download, FileText } from 'lucide-react'
import api from '../api/client'
import Modal from '../components/shared/Modal'
import Spinner from '../components/shared/Spinner'
import { useAuth } from '../hooks/useAuth'

const SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
const STATUS_COLORS = { PENDING: '#4a5568', GENERATING: '#f59e0b', COMPLETE: '#22c55e', FAILED: '#f87171' }

function ReportForm({ onSubmit, onCancel }) {
  const [title, setTitle] = useState('')
  const [caseRef, setCaseRef] = useState('')
  const [start, setStart] = useState('')
  const [end, setEnd] = useState('')
  const [severity, setSeverity] = useState('LOW')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!title || !caseRef) { setError('Title and case reference required'); return }
    setSaving(true)
    setError('')
    try {
      await onSubmit({
        title, case_reference: caseRef,
        start_date: start || null, end_date: end || null,
        severity_threshold: severity,
      })
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to queue report')
    } finally {
      setSaving(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label className="block text-xs font-mono text-[#8892a4] mb-1 uppercase tracking-wider">Report Title</label>
        <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Q4 2024 Counter-Extremism Summary" required />
      </div>
      <div>
        <label className="block text-xs font-mono text-[#8892a4] mb-1 uppercase tracking-wider">Case Reference</label>
        <input value={caseRef} onChange={(e) => setCaseRef(e.target.value)} placeholder="CASE-2024-001" required />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="block text-xs font-mono text-[#8892a4] mb-1 uppercase tracking-wider">Start Date</label>
          <input type="date" value={start} onChange={(e) => setStart(e.target.value)} />
        </div>
        <div>
          <label className="block text-xs font-mono text-[#8892a4] mb-1 uppercase tracking-wider">End Date</label>
          <input type="date" value={end} onChange={(e) => setEnd(e.target.value)} />
        </div>
      </div>
      <div>
        <label className="block text-xs font-mono text-[#8892a4] mb-1 uppercase tracking-wider">Min. Severity</label>
        <select value={severity} onChange={(e) => setSeverity(e.target.value)}>
          {SEVERITIES.map(s => <option key={s}>{s}</option>)}
        </select>
      </div>
      {error && <div className="text-xs font-mono text-[#f87171] bg-[#7f1d1d]/20 border border-[#7f1d1d]/40 px-3 py-2">{error}</div>}
      <div className="flex gap-2 pt-2">
        <button type="submit" disabled={saving} className="btn-primary py-1.5 px-5 disabled:opacity-50">
          {saving ? 'QUEUEING…' : 'GENERATE REPORT'}
        </button>
        <button type="button" onClick={onCancel} className="btn-secondary py-1.5 px-5">CANCEL</button>
      </div>
    </form>
  )
}

export default function Reports() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [showNew, setShowNew] = useState(false)
  const { isAnalyst } = useAuth()

  const load = () => {
    api.get('/api/reports').then((r) => setReports(r.data || [])).finally(() => setLoading(false))
  }

  useEffect(() => {
    load()
    const interval = setInterval(load, 10000) // Poll for status updates
    return () => clearInterval(interval)
  }, [])

  const handleGenerate = async (data) => {
    await api.post('/api/reports/generate', data)
    setShowNew(false)
    setTimeout(load, 2000)
  }

  const handleDownload = (report) => {
    window.open(`/api/reports/${report.id}/download`, '_blank')
  }

  if (loading) return <div className="flex justify-center pt-20"><Spinner label="Loading reports…" /></div>

  return (
    <div>
      <div className="flex items-center justify-between mb-5">
        <div className="text-xs font-mono text-[#4a5568] uppercase tracking-wider">
          {reports.length} report{reports.length !== 1 ? 's' : ''}
        </div>
        {isAnalyst && (
          <button onClick={() => setShowNew(true)} className="btn-primary flex items-center gap-2 py-1.5 px-4">
            <Plus size={13} /> GENERATE REPORT
          </button>
        )}
      </div>

      {reports.length === 0
        ? <div className="text-center py-16 text-[#4a5568] font-mono">NO REPORTS GENERATED YET</div>
        : (
          <table>
            <thead>
              <tr>
                <th>Case Reference</th><th>Title</th><th>Generated By</th>
                <th>Date</th><th>Status</th><th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.id}>
                  <td><span className="font-mono text-xs text-[#3b82f6]">{r.case_reference}</span></td>
                  <td className="text-xs text-[#e8eaf0]">{r.title}</td>
                  <td className="font-mono text-xs text-[#8892a4]">{r.generated_by}</td>
                  <td className="font-mono text-xs text-[#4a5568]">{r.generated_at?.slice(0, 16).replace('T', ' ')}</td>
                  <td>
                    <span
                      className="text-xs font-mono font-bold"
                      style={{ color: STATUS_COLORS[r.status] || '#8892a4' }}
                    >
                      {r.status === 'GENERATING' && <span className="animate-pulse">⬤ </span>}
                      {r.status}
                    </span>
                  </td>
                  <td>
                    {r.status === 'COMPLETE' && r.has_file && (
                      <button
                        onClick={() => handleDownload(r)}
                        className="flex items-center gap-1 text-xs font-mono text-[#3b82f6] hover:text-[#60a5fa]"
                      >
                        <Download size={12} /> PDF
                      </button>
                    )}
                    {r.status === 'GENERATING' && <Spinner size={12} />}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )
      }

      {showNew && (
        <Modal title="Generate Intelligence Report" onClose={() => setShowNew(false)} wide>
          <div className="text-xs font-mono text-[#f59e0b] border border-[#78350f]/40 bg-[#78350f]/10 px-3 py-2 mb-4">
            Report generation requires LLM analysis and may take 1–3 minutes.
          </div>
          <ReportForm onSubmit={handleGenerate} onCancel={() => setShowNew(false)} />
        </Modal>
      )}
    </div>
  )
}
